version: '3.0'
services:
  postgres:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=fortune_cookies
      - POSTGRES_USER=fortune_cookies
      - POSTGRES_DB=fortune_cookies