service:
  id: fortune-cookie-local
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fortune_cookies
    username: fortune_cookies
    password: fortune_cookies

flyway:
  url: jdbc:postgresql://localhost:5432/fortune_cookies
  user: fortune_cookies
  password: fortune_cookies
  enabled: true
  locations:
    - 'classpath:db/migration'
